name: Test and Package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and Test with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload Packaged JAR
        uses: actions/upload-artifact@v2
        with:
          name: plugin-binary
          path: target/*.jar
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: target/jacoco-ut/
